version: "3"

services:
  cpp:
    container_name: cpp
    stdin_open: true
    tty: true

    build:
      context: .
      dockerfile: Dockerfile

    ports:
      - "7000:7089"

    volumes:
      - .:/home/cpp-template

    environment:
      - NVIDIA_VISIBLE_DEVICES=all
      - JUPYTER_ENABLE_LAB=yes
      - NVIDIA_DRIVER_CAPABILITIES=all
